# Generated by Django 3.1.6 on 2021-04-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Entry1', models.TextField(max_length=20, null=True)),
                ('Entry2', models.TextField(max_length=20, null=True)),
                ('Entry3', models.TextField(max_length=20, null=True)),
                ('Entry4', models.TextField(max_length=20, null=True)),
                ('Entry5', models.TextField(max_length=20, null=True)),
                ('Entry6', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
