# Generated by Django 3.1.6 on 2021-05-16 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First', models.CharField(max_length=20, null=True)),
                ('Surname', models.CharField(max_length=20, null=True)),
                ('Email', models.EmailField(max_length=20, null=True)),
                ('Contact', models.IntegerField(null=True)),
                ('Address', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place', models.CharField(max_length=20, null=True)),
                ('Fee', models.IntegerField(null=True)),
                ('viewer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myWEB.sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Locations', models.CharField(max_length=20, null=True)),
                ('Charges', models.IntegerField(null=True)),
                ('viewer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myWEB.sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Donors', models.CharField(choices=[('Monetary Donation', 'Monetary Donation'), ('In-Kind Donation', 'In-Kind Donation')], max_length=20, null=True)),
                ('Message', models.TextField(max_length=50, null=True)),
                ('viewer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myWEB.sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='Monetary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('List', models.CharField(max_length=20, null=True)),
                ('Amount', models.CharField(max_length=20, null=True)),
                ('Gcash', models.CharField(max_length=20, null=True)),
                ('Bank', models.CharField(max_length=20, null=True)),
                ('Bills', models.TextField(max_length=50, null=True)),
                ('viewer', models.ManyToManyField(to='myWEB.Sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='Inkind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food', models.CharField(max_length=20, null=True)),
                ('Drinks', models.CharField(max_length=20, null=True)),
                ('Sanitation', models.CharField(max_length=20, null=True)),
                ('Cure', models.CharField(max_length=20, null=True)),
                ('Count', models.IntegerField(null=True)),
                ('Count1', models.IntegerField(null=True)),
                ('Count2', models.IntegerField(null=True)),
                ('Count3', models.IntegerField(null=True)),
                ('viewer', models.ManyToManyField(to='myWEB.Sponsor')),
            ],
        ),
    ]
