# Generated by Django 3.1.6 on 2021-06-11 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0002_auto_20210528_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundraising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organization', models.CharField(max_length=20, null=True)),
                ('Organizer', models.CharField(max_length=20, null=True)),
                ('Event', models.CharField(max_length=20, null=True)),
                ('Area', models.CharField(max_length=50, null=True)),
                ('Email', models.EmailField(max_length=20, null=True)),
                ('Time', models.DateField(max_length=20, null=True)),
                ('Sum', models.IntegerField(null=True)),
                ('viewer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myWEB.sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Receiver', models.CharField(max_length=20, null=True)),
                ('Dates', models.DateField(max_length=20, null=True)),
                ('Persons', models.CharField(max_length=20, null=True)),
                ('Contact', models.IntegerField(null=True)),
                ('Beneficiaries', models.IntegerField(null=True)),
                ('viewer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myWEB.sponsor')),
            ],
        ),
        migrations.DeleteModel(
            name='Guests',
        ),
        migrations.DeleteModel(
            name='Members',
        ),
        migrations.RemoveField(
            model_name='option',
            name='enters',
        ),
        migrations.DeleteModel(
            name='Enter',
        ),
    ]
