# Generated by Django 3.1.6 on 2021-04-24 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0002_auto_20210424_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Entry1',
            new_name='Donation',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Entry2',
            new_name='Donor',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Entry3',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Entry4',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Entry6',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Entry5',
            new_name='Type',
        ),
    ]
