# Generated by Django 3.1.6 on 2021-04-24 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0003_auto_20210424_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Item',
            new_name='Items',
        ),
    ]
