# Generated by Django 3.1.6 on 2021-06-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0003_auto_20210611_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraising',
            name='Item',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
