# Generated by Django 3.1.6 on 2021-06-13 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0004_fundraising_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='Message',
        ),
    ]
