# Generated by Django 3.1.6 on 2021-04-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0004_auto_20210424_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Type',
        ),
        migrations.AddField(
            model_name='item',
            name='Suport',
            field=models.CharField(choices=[('button1', 'Personal Donation'), ('button2', 'Company Donation')], default='none', max_length=10),
        ),
    ]
