# Generated by Django 3.1.6 on 2021-04-25 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0005_auto_20210425_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Suport',
            new_name='Support',
        ),
    ]
