# Generated by Django 3.1.6 on 2021-04-25 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0006_auto_20210425_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Support',
            new_name='bayan',
        ),
    ]
