# Generated by Django 3.1.6 on 2021-06-22 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0006_auto_20210613_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inkind',
            name='viewer',
        ),
        migrations.RemoveField(
            model_name='monetary',
            name='viewer',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='viewer',
        ),
    ]
