# Generated by Django 3.1.6 on 2021-04-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0007_auto_20210425_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='bayan',
            new_name='bayans',
        ),
    ]
