# Generated by Django 3.1.6 on 2021-06-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0008_settlement_viewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='inkind',
            name='viewer',
            field=models.ManyToManyField(to='myWEB.Sponsor'),
        ),
        migrations.AddField(
            model_name='monetary',
            name='viewer',
            field=models.ManyToManyField(to='myWEB.Sponsor'),
        ),
    ]
