# Generated by Django 3.1.6 on 2021-04-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0010_auto_20210425_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='support',
            field=models.CharField(choices=[('button1', 'tion'), ('button2', 'tion')], default='none', max_length=10),
        ),
    ]
