# Generated by Django 3.1.6 on 2021-04-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0011_auto_20210425_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='support',
            new_name='tion',
        ),
    ]
