# Generated by Django 3.1.6 on 2021-04-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0012_auto_20210425_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Donation',
        ),
        migrations.AddField(
            model_name='item',
            name='pick',
            field=models.CharField(choices=[('foods', 'foods'), ('drinks', 'drinks'), ('medicines', 'medicines'), ('clothes', 'clothes')], max_length=20, null=True),
        ),
    ]
