# Generated by Django 3.1.6 on 2021-04-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0013_auto_20210425_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='pick',
        ),
        migrations.AddField(
            model_name='item',
            name='Donation',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
