# Generated by Django 3.1.6 on 2021-04-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0014_auto_20210425_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='numbers',
            field=models.IntegerField(null=True),
        ),
    ]
