# Generated by Django 3.1.6 on 2021-06-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0015_remove_recipient_beneficiaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='chosen',
            field=models.CharField(choices=[('InKind Donations', 'InKind Donations'), ('Monetary Donations', 'Monetary Donations'), ('Both Donations', 'Both Donations')], max_length=20, null=True),
        ),
    ]
