# Generated by Django 3.1.6 on 2021-06-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0016_recipient_chosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='Contact',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
