# Generated by Django 3.1.6 on 2021-06-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0017_auto_20210624_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraising',
            name='Sum',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='Contact',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
