# Generated by Django 3.1.6 on 2021-06-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0018_auto_20210624_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundraising',
            old_name='Sum',
            new_name='Sums',
        ),
    ]
