# Generated by Django 3.1.6 on 2021-06-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0019_auto_20210624_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundraising',
            old_name='Sums',
            new_name='Summer',
        ),
    ]
