# Generated by Django 3.1.6 on 2021-06-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0020_auto_20210624_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundraising',
            old_name='Summer',
            new_name='Sum',
        ),
    ]
