# Generated by Django 3.1.6 on 2021-06-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0022_auto_20210624_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipient',
            old_name='List',
            new_name='What',
        ),
    ]
