# Generated by Django 3.1.6 on 2021-06-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0023_auto_20210624_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipient',
            old_name='What',
            new_name='Specify',
        ),
    ]
