# Generated by Django 3.1.6 on 2021-06-24 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0024_auto_20210624_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monetary',
            name='Amount',
        ),
    ]
