# Generated by Django 3.1.6 on 2021-06-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0025_remove_monetary_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipient',
            old_name='Specify',
            new_name='Specifics',
        ),
    ]
