# Generated by Django 3.1.6 on 2021-06-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWEB', '0026_auto_20210624_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipient',
            old_name='Specifics',
            new_name='haha',
        ),
    ]
